FROM golang:1.25-alpine

WORKDIR /app

# Install git and other utilities
RUN apk add --no-cache git gcc musl-dev

# Install air for live reloading
RUN go install github.com/air-verse/air@latest

# Copy go mod and download dependencies
# We'll mount the rest of the source code
COPY go.mod ./
# RUN go mod download # (Wait until there are dependencies)

CMD ["air", "-c", ".air.toml"]
